name: Terraform
on: [push]
jobs:
  check-format:
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive -diff
        continue-on-error: true

  validate:
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
	id: init
        run: terraform init -upgrade
        working-directory: examples/test
      - name: Terraform Validate
	id: validate
        run: terraform validate
        working-directory: examples/test
	continue-on-error: true

  mock-plan:
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
	id: init
        run: terraform init -upgrade
        working-directory: examples/test
      - name: Terraform Plan (Mock)
	id: plan
        run: terraform plan
        working-directory: examples/test
	continue-on-error: true

  infracost:
    name: Show infracost diff
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@master
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: examples/test

